chore: migrate to upstream chart, add `unicorn` CGR flavor
defenseunicorns/uds-package-sonarqube pull request #100
Opened 2024-07-18 18:44 UTC by marshall007

## Description

## Related Issue

Fixes #82
Fixes #96

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-sonarqube/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-07-18 18:52 UTC, zachariahmiller requested changes

2024-07-18 18:52 UTC, zachariahmiller commented on values/common-values.yaml
> +  # postgresqlServer: ###ZARF_VAR_SONARQUBE_DB_ENDPOINT###
these cant be comment out and still work with the zarf var templating

2024-07-18 18:52 UTC, zachariahmiller commented on values/unicorn-values.yaml
> +image:
This isnt actually getting published or tested anywhere. 

See https://github.com/defenseunicorns/uds-core/blob/cacf1b5d8bccd16a8c2381fbd0912715a78a22c2/.github/workflows/publish.yaml#L15

https://github.com/defenseunicorns/uds-core/blob/cacf1b5d8bccd16a8c2381fbd0912715a78a22c2/.github/workflows/publish.yaml#L77

(test needs existing release to test upgrade first)
https://github.com/defenseunicorns/uds-core/blob/cacf1b5d8bccd16a8c2381fbd0912715a78a22c2/.github/workflows/pull-request-conditionals.yaml#L79

2024-07-18 18:54 UTC, zachariahmiller commented on values/common-values.yaml
> +prometheusExporter:
Did you test that this is working? I would assume based on my previous work that it is not, so we should probably leave it off until monitoring is implemented properly (either here or in another PR associated with the issue related to getting it working)

2024-07-18 18:55 UTC, zachariahmiller commented on values/common-values.yaml
> +    enabled: true
same as other comment on monitoring

2024-07-18 20:41 UTC, marshall007 commented on values/common-values.yaml
> +  # postgresqlServer: ###ZARF_VAR_SONARQUBE_DB_ENDPOINT###
These values are not needed anymore (I don't think). I just commented them out until I'm sure and the tests pass.

2024-07-19 14:55 UTC, zachariahmiller commented on chart/templates/uds-package.yaml
> +        monitoringPasscode: {{ .Values.monitoringPasscode }}
The monitoring passcode is needed for SSO?

2024-07-19 14:59 UTC, zachariahmiller requested changes

2024-07-19 14:59 UTC, zachariahmiller commented on bundle/uds-bundle.yaml
> +            - path: "monitoringPasscodeSecretName"
I think we should probably generate the monitoring passcode in the config chart and then default these values in the upstream chart [values](https://github.com/SonarSource/helm-chart-sonarqube/blob/a201d5911f5819c5cfa3433536e420cab3911909/charts/sonarqube/values.yaml#L375) so it will get set to something good/random by default rather than requiring overrides or being added to the sso secret via a values entry in both charts. 🤔

2024-07-19 15:50 UTC, zachariahmiller commented on values/common-values.yaml
> +  # postgresqlServer: ###ZARF_VAR_SONARQUBE_DB_ENDPOINT###
You'll need to reach out to folks and make sure they are not being used then as its a breaking change in the interface with our consumers.

2024-07-23 18:15 UTC, marshall007 commented on values/common-values.yaml
> +prometheusExporter:
I have disabled for now. Would you like me to remove the related config?

2024-07-23 18:45 UTC, marshall007 commented on values/unicorn-values.yaml
> +image:
I think this is resolved with changes to uds-common in `v0.8.1` that were pulled in.

2024-07-23 18:50 UTC, marshall007 commented on .github/workflows/test.yaml
> +            type: upgrade
This would probably be more clear with:

```yaml
exclude:
  - flavor: unicorn
    type: upgrade
```

2024-07-24 18:26 UTC, marshall007 commented on values/common-values.yaml
> +  # postgresqlServer: ###ZARF_VAR_SONARQUBE_DB_ENDPOINT###
I confirmed with @anthonywendt that this config for the nested chart is unnecessary. I'll remove the comments shortly.

2024-07-24 19:37 UTC, marshall007 commented on tasks/test.yaml
> +          echo "SonarQube migration state: ${STATUS}"
@Racer159 I just made this a UDS task rather than performing the upgrade in the zarf package. The docs recommend performing a full DB backup prior to running migrations, so it did not seem safe to do by default.

2024-07-24 20:05 UTC, Racer159 requested changes

2024-07-24 20:05 UTC, Racer159 commented on values/common-values.yaml
> +#   configureNode: false
Just delete

2024-07-24 20:05 UTC, Racer159 commented on values/common-values.yaml
> +  enable: true # DEPRECATED: use `jdbcOverwrite.enabled` in v10.7.0
delete

2024-07-24 20:05 UTC, Racer159 commented on zarf.yaml
> +  version: "10.6.0-uds.0"
let release please handle

2024-07-24 20:05 UTC, Racer159 commented on .github/workflows/tag-and-release.yaml
>          run: uds run -f tasks/publish.yaml package --set FLAVOR=${{ matrix.flavor }} --no-progress
w/o a change to the publish task this will put the CGR flavor in the wrong spot

2024-07-24 20:05 UTC, Racer159 commented on .github/workflows/test.yaml
> +    runs-on: uds-swf-ubuntu-big-boy-4-core
disk?

2024-07-24 20:05 UTC, Racer159 commented on tasks/test.yaml
> +          echo "SonarQube migration state: ${STATUS}"
This is fine but should be mentioned in the release announcement / breaking changes

2024-07-24 20:05 UTC, Racer159 commented on tests/auth.setup.ts
> -  await expect(page).toHaveURL('/projects');
does it not redirect back to a page anymore?

2024-07-24 20:09 UTC, marshall007 commented on values/common-values.yaml
> +  enable: true # DEPRECATED: use `jdbcOverwrite.enabled` in v10.7.0
Current chart version is `10.6.1`, they are switching to `enabled` in the next version but it doesn't work yet. I was just future-proofing because this got me in testing.

2024-07-24 20:10 UTC, marshall007 commented on tests/auth.setup.ts
> -  await expect(page).toHaveURL('/projects');
It redirects to `/projects` if you have any projects and `/projects/create` if you don't. This lets the auth test pass in either case.

2024-07-24 20:38 UTC, marshall007 commented on .github/workflows/tag-and-release.yaml
>          run: uds run -f tasks/publish.yaml package --set FLAVOR=${{ matrix.flavor }} --no-progress
https://github.com/defenseunicorns/uds-core/blob/main/tasks/utils.yaml#L11

2024-07-25 17:13 UTC, marshall007 commented on tasks.yaml
> +          target_repo: ${TARGET_REPO}
Is there a better way to do this? Seems gross that every task that has `target_repo` as an input is going to need this treatment.

2024-07-30 17:15 UTC, marshall007 commented on .github/workflows/tag-and-release.yaml
>          run: uds run -f tasks/publish.yaml package --set FLAVOR=${{ matrix.flavor }} --no-progress
Done in https://github.com/defenseunicorns/uds-common/pull/188

2024-07-30 20:22 UTC, Racer159 approved these changes
tested locally and behavior was as expected

2024-07-30 20:32 UTC, zachariahmiller approved these changes

2024-07-30 22:18 UTC, merged