chore: change to use uds-common test action
defenseunicorns/uds-package-sonarqube pull request #54
Opened 2024-03-12 14:46 UTC by ericwyles

## Description

Updated the test workflow to use new test action from uds-common

Updated other uds-common references to the latest version.

Renamed pull-requests.yaml to test.yaml to match other packages

## Related Issue
Relates to https://github.com/defenseunicorns/uds-software-factory/issues/17

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-sonarqube/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-03-12 18:27 UTC, Racer159 requested changes
partial review before mtg.

2024-03-12 18:27 UTC, Racer159 commented on .github/workflows/tag-and-release.yaml
>            username: dummy
This should have save-logs as well after line `52`

2024-03-12 19:25 UTC, Racer159 requested changes
rest of comments

2024-03-12 19:25 UTC, Racer159 commented on .github/workflows/test.yaml
> +      - "zarf.yaml"
We should standardize these onto the type of file (i.e. `**.md`) IMO like mattermost instead of folder. That would allow us to be more flexible with when these run no matter where those files might be.

2024-03-12 19:25 UTC, Racer159 commented on tasks.yaml
>        - task: setup-cluster
We might as well standardize these includes to pull from uds-common v0.2.2 like gitlab

2024-03-12 21:20 UTC, ericwyles commented on tasks.yaml
>        - task: setup-cluster
Updated.

2024-03-12 21:20 UTC, ericwyles commented on .github/workflows/test.yaml
> +      - "zarf.yaml"
Updated.

2024-03-12 21:20 UTC, ericwyles commented on .github/workflows/tag-and-release.yaml
>            username: dummy
Updated.

2024-03-13 01:14 UTC, zachariahmiller commented
@ericwyles updated the required checks. Looks like the doc shim isnt in this one yet so not concerns there. I pinged @Racer159 to also approve/dismiss his request for changes. Thanks!

2024-03-13 01:14 UTC, zachariahmiller approved these changes

2024-03-13 02:23 UTC, Racer159 approved these changes

2024-03-13 02:32 UTC, merged